# Generated by Django 3.1.7 on 2021-03-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default=1, max_length=50, verbose_name='Вес стандартной модели'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='contry',
        ),
        migrations.AddField(
            model_name='product',
            name='contry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shop.produсtcontry',
                                    verbose_name='Старана производитель'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shop.productmaterial',
                                    verbose_name='Материал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='model_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID товара'),
        ),
    ]
